import { palette } from '@/theme/tokens';

import type { ThemeContract } from './theme.contract';

export const lightTheme: ThemeContract = {
  name: 'light',
  density: 'comfortable',
  radiusStyle: 'rounded',
  typography: {
    fontFamily: {
      regular: 'Pretendard-Regular',
      medium: 'Pretendard-Medium',
      bold: 'Pretendard-Bold',
    },
    scale: 1,
  },
  colors: {
    background: {
      base: palette.stitch.light.bg,
      surface: palette.stitch.light.surface,
      elevated: palette.stitch.light.surface,
      sunken: '#f1f5f9',
      overlay: 'rgba(15, 23, 42, 0.5)',
      input: palette.white,
      media: '#FAFAFA',
    },
    text: {
      primary: palette.stitch.light.text,
      secondary: palette.stitch.light.secondary,
      tertiary: '#94a3b8',
      muted: '#94a3b8',
      soft: '#94a3b8',
      disabled: '#cbd5e1',
      inverse: '#FFFFFF',
      link: palette.stitch.primary,
      gray: palette.theme.gray[80],
      title: palette.theme.gray[80],
      pageHeaderTitle: palette.theme.gray[90],
      label: palette.theme.gray[30],
      input: palette.theme.gray[30],
    },
    action: {
      primary: {
        default: palette.stitch.primary,
        pressed: '#0f0fdb',
        disabled: '#cbd5e1',
        label: '#FFFFFF',
      },
      secondary: {
        default: palette.blue[50],
        pressed: palette.blue[100],
        disabled: palette.theme.gray[5],
        label: palette.blue[700],
      },
      ghost: {
        default: 'transparent',
        pressed: palette.theme.gray[5],
        disabled: 'transparent',
        label: palette.theme.gray[30],
      },
    },
    feedback: {
      success: {
        bg: palette.green[50],
        text: palette.green[700],
        border: palette.green[200],
      },
      error: {
        bg: palette.red[50],
        text: palette.red[700],
        border: palette.red[200],
      },
      warning: {
        bg: palette.yellow[50],
        text: palette.yellow[900],
        border: palette.yellow[200],
      },
      info: {
        bg: palette.blue[50],
        text: palette.blue[700],
        border: palette.blue[200],
      },
    },
    tag: {
      critical: {
        700: palette.tag.critical[700],
      },
    },
    border: {
      default: palette.stitch.light.border,
      strong: '#e2e8f0',
      subtle: '#f8fafc',
      focus: palette.stitch.primary,
      divider: '#f1f5f9',
      input: '#e2e8f0',
    },
    field: {
      label: palette.theme.gray[70],
      required: palette.theme.blue[50],
      optional: palette.theme.softBlue[50],
      placeholder: palette.theme.gray[10],
      text: palette.theme.gray[70],
      icon: palette.theme.blue[50],
      border: palette.theme.gray[70],
      background: palette.white,
    },
    questDetail: {
      periodBackground: palette.theme.gray[95],
      periodText: palette.theme.gray[10],
    },
    brand: {
      grey: '#636e72',
      background: '#F5F7FA',
      backgroundGrey: '#FFFFFF',
      primary: '#0984e3',
      secondary: '#0984e3',
      text: '#2D3436',
      textSecondary: '#636e72',
      icon: '#2D3436',
      button: '#0984e3',
      buttonLight: '#FFFFFF',
      subButton: '#b2bec3',
      checkbox: '#0984e3',
      check: '#0984e3',
      selectedCheckbox: '#0984e3',
      selectedCheck: '#0984e3',
      todaySuccessCheckbox: palette.theme.blue[10],
      todaySuccessCheck: palette.theme.blue[80],
      pendingConfirmationCheckbox: palette.yellow[100],
      pendingConfirmationCheck: palette.yellow[700],
      input: '#F5F7FA',
      error: '#d63031',
      success: '#00b894',
      warning: '#fdcb6e',
      info: '#0984e3',
      border: '#2D3436',
      boxShadow: '0 4px 0 rgba(45, 52, 54, 0.5)',
      foreground: '#2D3436',
      root: '#F5F7FA',
      card: '#FFFFFF',
      bottomTab: '#FFFFFF',
      activeBottomTab: '#FFFFFF',
      routineBorder: palette.theme.blue[80],
      routineBackground: '#FFFFFF',
      routineMissedCheckbox: palette.theme.blue[90],
      routineUpcomingCheckboxBorder: palette.theme.softBlue[80],
    },
  },
};
